### ISSUE TITLE
Description is still 'Office 365 CLI'

### ISSUE THREAD

**Issue by Abderahman88** [pnp/action-cli-runscript#10]
How come the description is not updated to `CLI for Microsoft 365` ? (Tested in Chrome and Edge)

![image](https://user-images.githubusercontent.com/36161889/140662898-c3bc57db-9d32-4119-b8f8-ec088a6f96bf.png)

**Comment by garrytrinder** [comment]
Good catch @Abderahman88 ❤️

I've updated 👍🏻
