### ISSUE TITLE
Update the documentation to use master instead of v1.0.0

### ISSUE THREAD

**Issue by VelinGeorgiev** [pnp/action-cli-runscript#4]
Description: Update the documentation where the examples use `master` instead of `v.1.x.x`. Change from `pnp/action-cli-runscript@v1.0.0` to `pnp/action-cli-runscript@master`.

This will guarantee that users that follow the docs get the latest version of the action with all the fixes and enhancements.

**Comment by waldekmastykarz** [comment]
Wouldn't this be unsafe in case we'd release a v2 with breaking changes?

**Comment by VelinGeorgiev** [comment]
We can have best of both worlds, can't we? 😄 

The more I think about this the more I think that we should leave it declarative as is. We could introduce separate branch `v1` instead of `master`, but then we would create ambiguity again where the people will wonder why we have short and full versions. 

I will close this in favor of what we did so far. The users will have to update the versions in their pipelines if they'd like to accept new updates and hot-fixes for now.

**Comment by waldekmastykarz** [comment]
If actions use semver, then we could perhaps use `pnp/action-cli-runscript@v1` which would allow people to automatically get fixes, without having the risk of us breaking their scripts due to a major version release.
